Aca 68
hmcts/ccd-data-store-api pull request #1221
Opened 2020-11-17 12:46 UTC by sullivangareth

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-11-17 15:16 UTC, mattnayler reviewed
If jenkins reports shows as all green: and hmcts/befta-fw#118 OK: then approved if updated to reflect final `befta-fw` release version.

2020-11-17 15:25 UTC, mattnayler requested changes
approved if updated to reflect final befta-fw release version.

2020-11-18 19:13 UTC, tomxelliott approved these changes

2020-11-19 08:47 UTC, mattnayler approved these changes

2020-12-11 09:13 UTC, sullivangareth commented
Closing old redundant PR

2020-12-11 09:13 UTC, closed without merging