Release-cut 20.2 Revised
hmcts/ccd-data-store-api pull request #1244
Opened 2020-11-27 00:30 UTC by hemantt

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/projects/RDM/versions/36004

### Change description ###
**Revised list of Version 20.2** 

Bug

    [RDM-8698] - Elasticsearch exact match queries on phone numbers with spaces never return results
    [RDM-9824] - ChallengeQuestion tab issues

Feature

    [RDM-7484] - Add Support for Concurrent Execution of Test Suites

Task

    [RDM-9200] - FTA for Swagger Documentation and API Specs - Data Store API
    [RDM-9533] - Improve performance of LS Sweeper
    [RDM-9694] - CCD Logstash to index cases in state DRAFT in Elasticsearch
    [RDM-9696] - Create Liquibase Changeset For Additional Indexes
    [RDM-9741] - Revert Changes of RDM-9338
    [RDM-9910] - Fix Logstash "ghost cases" indexing issue
    [RDM-10321] - Enable Persistent Queue for Logstash
    [RDM-10389] - Release 20.2 Perftest/Demo deployment and Testing

Improvement

    [RDM-9343] - Elasticsearch sorts are case-sensitive

TechDebt

    [RDM-9939] - Move Organisation Policy validation from DefaultValidateCaseFieldsOperation to a dedicated validator
    [RDM-9954] - Remove no longer needed "defaultValue" field from API response

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-11-27 10:26 UTC, danlysiak requested changes
Couple of minor things

2020-11-27 10:26 UTC, danlysiak commented on charts/ccd-data-store-api/values.preview.template.yaml
> +>>>>>>> f5846dfe7... Update def store wiring
Needs resolving 😄

2020-11-27 10:26 UTC, danlysiak commented on src/main/resources/db/changelog/db.changelog-master.xml
>      <include file="db/changelog/db.changelog-RDM-9505.xml"/>
Think we're missing a line in here for RDM-9696 (two files up from this one)?

2021-01-08 12:51 UTC, danlysiak approved these changes

2021-01-08 15:52 UTC, mario-paniccia approved these changes
👍

2021-01-11 22:06 UTC, merged