RDM-10569 Extend Data Reuse Within The Data Store
hmcts/ccd-data-store-api pull request #1281
Opened 2020-12-10 11:21 UTC by Abi-Laver

https://tools.hmcts.net/jira/browse/RDM-10569

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2021-01-12 14:06 UTC, MSancaktutar requested changes
Could you please fix the indentation of the json files? They look broken with tabs/spaces in many places. Otherwise ok.

2021-01-12 15:44 UTC, MSancaktutar approved these changes
LGTM

2021-01-13 08:47 UTC, noronhaa approved these changes

2021-01-13 09:30 UTC, danlysiak approved these changes

2021-01-13 10:52 UTC, merged