RDM-11213: Disregard [CREATOR] role
hmcts/ccd-data-store-api pull request #1379
Opened 2021-02-22 17:13 UTC by tomxelliott

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-11213

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-24 09:11 UTC, MSancaktutar commented on src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
> +                            && !caseUserRole.getCaseRole().equals(CREATOR.getRole()))
`equalsIgnoreCase` will be safer.

2021-02-24 09:18 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
> +        @DisplayName("should not increment organisation user count for single new case-user with [CREATOR] role")
Adding a decrement test could also be useful, couldn't it?

2021-02-24 09:18 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
> +        @DisplayName("should increment organisation user count for new case-user relationship without [CREATOR] role")
Adding a decrement test could also be useful, couldn't it?

2021-02-24 09:19 UTC, MSancaktutar requested changes
Pls see my 3 comments.

2021-02-24 15:36 UTC, MSancaktutar approved these changes
LGTM

2021-02-25 08:46 UTC, danlysiak approved these changes
👍

2021-02-25 13:22 UTC, merged

2021-02-25 13:22 UTC, MSancaktutar commented
Merged as confirmed by QA.