Rdm 10737 (temp branch)
hmcts/ccd-data-store-api pull request #1380
Opened 2021-02-22 20:18 UTC by sullivangareth

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-23 17:13 UTC, mattnayler requested changes
LGTM 👍 .  However please confirm or reset relevant Jenkins and chart changes prior to merger.

2021-02-23 17:21 UTC, sullivangareth commented on Jenkinsfile_nightly
> +env.ELASTIC_SEARCH_FTA_ENABLED = "true"
No, I will change this back

2021-02-23 17:21 UTC, sullivangareth commented on Jenkinsfile_CNP
> +env.ELASTIC_SEARCH_FTA_ENABLED = "true"
Yes, I will revert this back to its original value

2021-02-23 17:21 UTC, sullivangareth commented on Jenkinsfile_CNP
> +def dataStoreApiDevelopPr    = "PR-1380" // This doesn't change frequently, but when it does, only change this value.
Yes

2021-02-23 17:22 UTC, sullivangareth commented on charts/ccd-data-store-api/values.preview.template.yaml
> +    DEFINITION_STORE_HOST: http://ccd-definition-store-api-pr-948.service.core-compute-preview.internal/
Yes they will

2021-02-23 17:28 UTC, mattnayler approved these changes
Approved **subject to [my previous comments](https://github.com/hmcts/ccd-data-store-api/pull/1380#pullrequestreview-596547297) being addressed as required during checkpoint**

2021-02-24 11:54 UTC, MSancaktutar approved these changes
LGTM, but please push a commit just before merging to restore the wiring and ES-enablement changes.

2021-02-25 16:34 UTC, merged