CCD-1263 CVE-2021-22118 in CCD Data Store API
hmcts/ccd-data-store-api pull request #1522
Opened 2021-06-09 12:33 UTC by skandala-cgi

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CCD-1263

### Change description ###
CVE-2021-22118 in CCD Data Store API

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-06-11 02:01 UTC, MSancaktutar approved these changes
LGTM

2021-06-11 09:06 UTC, MSancaktutar approved these changes
LGTM

2021-06-19 20:55 UTC, MSancaktutar approved these changes
LGTM

2021-06-20 15:17 UTC, danlysiak commented on build.gradle
> +        springBootVersion = '2.4.4'
⚠️ Updating to Spring Boot 2.4 will require further changes to move to the reading of secrets (same changes as per Slack discussion).
https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4

2021-06-20 15:18 UTC, danlysiak requested changes

2021-06-20 15:18 UTC, danlysiak commented on build.gradle
> +        springBootVersion = '2.4.4'
⚠️ Updating to Spring Boot 2.4 will require further changes to move to the reading of secrets (same changes as per Slack discussion).
https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4

2021-06-22 16:43 UTC, skandala-cgi commented
Raised a new one

2021-06-22 16:43 UTC, closed without merging