RDM-12741: AC FTA - Create MVP Scenarios for get Case
hmcts/ccd-data-store-api pull request #1650
Opened 2021-09-12 23:03 UTC by kiran-yenigala-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-12741

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2021-09-14 13:18 UTC, Thor-tech-of-metal commented
Kiran  you will need to rebase on to of RDM-12732 .  This is ashley pr , I mergend my pr there . RDM-12732

2021-09-14 13:21 UTC, noronhaa requested changes
- base file for get case endpoint files
- base file for grant role assignment files
-  prefix grant role assignment files with feature file tag/number

2021-09-14 13:21 UTC, noronhaa commented on src/aat/resources/features/F-201 - New Access Control Get Case/F-201_CT1.td.json
> +  "productName": "CCD Data Store",
for all files using the /case-types/{ctid}/cases endpoint lets create and extend a base file like F-201_GetCaseBase.td.json and put the common lines of code here like the api details and request headers, then we can remove this common lines from all the files extending them

2021-09-14 13:21 UTC, noronhaa commented on src/aat/resources/features/F-201 - New Access Control Get Case/F-201_CT1.td.json
> +      "password": "Pa55word11"
lets hide all of the passwords with [[$CCD_BEFTA_CASEWORKER_1_PWD]] for now

2021-09-14 13:21 UTC, noronhaa commented on src/aat/resources/features/F-201 - New Access Control Get Case/Grant_Role_Assignment.td.json
> +  "_guid_" : "GRANT_CASE_ROLE_ASSIGNMENT",
for all files using the /am/role-assignments  endpoint lets create and extend a base file like F-201_GrantRoleAssignment.td.json and put the common lines of code here like the api details and request headers, then we can remove this common lines from all the files extending them

2021-09-14 13:21 UTC, noronhaa commented on src/aat/resources/features/F-201 - New Access Control Get Case/Grant_Role_Assignment.td.json
> +  "uri": "http://localhost:4096/am/role-assignments",
we need to make this host dynamic or env var  as this wont work i higher up envs. we can use ROLE_ASSIGNMENT_HOST env var

2021-09-14 13:21 UTC, noronhaa commented on src/aat/resources/features/F-201 - New Access Control Get Case/Grant_Role_Assignment.td.json
> +  "_guid_" : "GRANT_CASE_ROLE_ASSIGNMENT",
Lets prefix the file name and guid with F201_ as these files are unique to this set of tests

2021-09-14 14:03 UTC, Thor-tech-of-metal reviewed
I also noticed the need to add a base json files.

2021-09-23 13:43 UTC, Thor-tech-of-metal approved these changes

2022-02-24 18:10 UTC, closed without merging