RDM-12981: Update V2 Start Event API
hmcts/ccd-data-store-api pull request #1742
Opened 2021-11-26 11:56 UTC by kiran-yenigala-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-12981

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2021-11-26 13:07 UTC, rafalkalita requested changes
Looks good, but worth updating the unit test.

2021-11-26 13:07 UTC, rafalkalita commented on src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseUpdateViewEventBuilder.java
> +        caseUpdateViewEvent.setSupplementaryData(startEventResult.getCaseDetails().getSupplementaryData());
Could we update the CaseUpdateViewEventBuilderTest.shouldBuildTrigger() ?

2021-11-29 09:02 UTC, danlysiak approved these changes
Approved assuming @rafalkalita's requested change to be made

2022-01-24 11:01 UTC, rafalkalita approved these changes

2022-02-01 14:12 UTC, merged