CCD-2539: Cache system user token
hmcts/ccd-data-store-api pull request #1845
Opened 2022-02-08 13:22 UTC by paulridout

### JIRA link (if applicable) ###
CCD-2539 (https://tools.hmcts.net/jira/browse/CCD-2539)

### Change description ###
Added Cacheable annotation to IdamRepository getDataStoreSystemUserAccessToken().  This caches the system user access token and reduces the number of calls made to IDAM.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-02-08 18:26 UTC, kaanaktas approved these changes
lgtm

2022-02-09 10:27 UTC, MSancaktutar requested changes
Could we please add some unit/integration test for this?
Otherwise nice one.

2022-02-15 14:12 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/ccd/integrations/IdamRepositoryCachingIT.java
> +            TimeUnit.SECONDS.sleep(3);
5 or 6 sec could be good enough, as TTL is 3 sec.

2022-02-15 14:15 UTC, MSancaktutar requested changes
1 comment to be addressed please, otherwise looks good. I'll progress this to QA now, while a tiny commit is to come.

2022-02-15 14:16 UTC, paulridout commented on src/test/java/uk/gov/hmcts/ccd/integrations/IdamRepositoryCachingIT.java
> +            TimeUnit.SECONDS.sleep(3);
Will change to 5 seconds.  That should give enough margin.

2022-02-16 13:48 UTC, merged