CCD-3533 auto create new suppression for cve
hmcts/ccd-data-store-api pull request #2071
Opened 2022-08-11 16:02 UTC by marvincudjoe

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CCD-3533

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-08-12 15:32 UTC, danlysiak commented on .github/workflows/dependency-check.yml
> +          branch: 'develop'
```suggestion
          branch: 'master'
```

2022-08-12 15:33 UTC, danlysiak commented on .github/workflows/dependency-check.yml
> +    - cron: "05 8-16/3 * * 1-5" # On the 5th minute, every 3 hours, from 8am to 4pm
I think we should do this throughout the night too, to reduce the risk of nightly pipelines failing as well - every 3 hours sounds reasonable though!

2022-08-12 15:35 UTC, danlysiak commented on .github/workflows/dependency-check.yml
> +    - cron: "05 8-16/3 * * 1-5" # On the 5th minute, every 3 hours, from 8am to 4pm
I think we should do this in a wider time period, to reduce the risk of nightly pipelines failing as well - every 3 hours sounds reasonable though!
```suggestion
    - cron: "05 6-18/3 * * 1-5" # On the 5th minute, every 3 hours, from 8am to 4pm
```

2022-08-12 18:03 UTC, paulridout reviewed
Am I right in thinking that this creates a new <suppress> section for each new CVE rather than appending to a single existing <suppress> section?  The Jira ticket mentions that the proof of concept didn't quite match the proposal, so I was just wondering if this uses the proof of concept approach.

2022-08-31 11:38 UTC, danlysiak approved these changes

2022-10-04 13:21 UTC, kaanaktas reviewed
Do we duplicate suppressions, even if they already exist? This is what I understood from the comment on the ticket.

2022-10-06 09:12 UTC, kaanaktas approved these changes
lgtm

2022-10-17 10:27 UTC, rajaram-nagarajan requested changes

2022-10-17 10:27 UTC, rajaram-nagarajan commented on .github/workflows/dependency-check.yml
> +    - cron: "H 6-18/3 * * 1-5"
@marvincudjoe - we can run this over the weekends too

2022-10-17 10:27 UTC, rajaram-nagarajan commented on .github/workflows/dependency-check.yml
> +    - cron: "H 6-18/3 * * 1-5"
@marvincudjoe Let's run from 10AM to 12AM

2022-11-22 17:16 UTC, rajaram-nagarajan approved these changes
LGTM

2022-11-23 11:39 UTC, merged