Ga 13 filter by case access group
hmcts/ccd-data-store-api pull request #2333
Opened 2023-11-16 15:12 UTC by sanjayparekh-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the `keep-helm` label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/GA-13

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-11-23 14:42 UTC, abul-syed commented on src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
> +        return MatcherType.ROLENAME;
```suggestion
        return MatcherType.CASEACCESSGROUPID;
```

2023-11-23 14:44 UTC, abul-syed commented on src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
> +    private static final Logger LOG = LoggerFactory.getLogger(CaseAccessGroupsMatcher.class);
```suggestion
```
not required, class already annotated with lombok annotation `@Slf4j`

2023-11-23 14:46 UTC, abul-syed commented on src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
> +        LOG.info("Match role assignment caseAccessGroupId {} with caseAccessGroupIds {} for role assignment {}",
```suggestion
        log.info("Match role assignment caseAccessGroupId {} with caseAccessGroupIds {} for role assignment {}",
```
using `@Slf4j`

2023-11-23 14:58 UTC, abul-syed commented on src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
> +        LOG.info("Match role assignment caseAccessGroupId {} with caseAccessGroupIds {} for role assignment {}",
```suggestion
        log.debug("Match role assignment caseAccessGroupId {} with caseAccessGroupIds {} for role assignment {}",
```

probs best to switch to `debug` level prior to master merge

2023-11-23 14:59 UTC, abul-syed commented on src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
> +        log.info("Role assignment caseAccessGroupId {} and case details caseAccessGroupIds {} match {}",
```suggestion
        log.debug("Role assignment caseAccessGroupId {} and case details caseAccessGroupIds {} match {}",
```
same comment as above - `debug` level

2023-11-23 15:08 UTC, abul-syed commented on src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
> +    private static final String CASE_ACCESS_GROUP_ID_FIELD = "caseAccessGroupId";
should the static fields be moved to the interface?

2023-11-23 15:16 UTC, abul-syed requested changes
few changes

2023-12-04 09:56 UTC, helenbirdhmcts approved these changes
Looks good, approved pending tests added by QA

2024-03-06 12:46 UTC, RebeccaBaker approved these changes

2024-03-06 15:05 UTC, merged